### ISSUE TITLE
#denokv kv.watch epic

### ISSUE THREAD

**Issue by rbetts** [denoland/denokv#27]

**Comment by rbetts** [comment]
Epic placeholder for `kv.watch`.

- [ ] Preproduction review link [TBD]
- [ ] CLI: https://github.com/denoland/deno/pull/21147
- [ ] KV Connect: https://github.com/denoland/denokv/pull/26
